refactor(preventDoubleAction): update anonymous component feature introduced in circom 2.1.0
FoodChain1028/Unirep pull request #3
Opened 2023-08-27 06:58 UTC by moven0831

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally in root directory and any changes were pushed
- [ ] Lint (`yarn lint:fix`) was run locally in root directory and any changes were pushed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

This PR modifies the circom styling from previous version to the newest (^2.1.0).

Previous Version
```
template A(n){
   signal input a, b;
   signal output c;
   c <== a*b;
}
template B(n){
   signal input in[n];
   signal out;
   component temp_a = A(n);
   temp_a.a <== in[0]; 
   temp_a.b <== in[1];
   out <== temp_a.c;
}
component main = B(2);
```

New version
```
template A(n){
   signal input a, b;
   signal output c;
   c <== a*b;
}
template B(n){
   signal input in[n];
   signal out <== A(n)(in[0],in[1]);
}
component main = B(2);
```

By doing so, we could increase the readability of the code and make the code much neater to maintain.

Issue Number: #530 

## What is the new behavior?

The behavior of the modification should not change any result from the previous version.  

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2023-08-27 08:13 UTC, Yingyu18 approved these changes
LGTM.
Passed the test.

2023-08-27 15:54 UTC, FoodChain1028 commented on packages/circuits/circuits/preventDoubleAction.circom
> +    signal commitment_secret;
I suggest using `identity_secret` to config the same signal in `IdentityCommitment()`

2023-08-27 15:57 UTC, FoodChain1028 requested changes
Looks Great!! Yet there are several parts that can be improved in my view 😆.

2023-08-27 15:57 UTC, FoodChain1028 commented on packages/circuits/package.json
> +        "refresh": "find ./zksnarkBuild -type f -not -name 'powersOfTau28_hez_final_18.ptau' -delete && yarn build"
it can be modified into the newest version!

2023-08-28 03:17 UTC, C1em3nt approved these changes
LGTM

2023-08-28 03:37 UTC, moven0831 reviewed
Hi @FoodChain1028 , I've renamed variable `commitment_secret` to `identity_secret`.

2023-08-28 03:37 UTC, moven0831 commented on packages/circuits/circuits/preventDoubleAction.circom
> +    signal commitment_secret;
That makes sense. Thanks for review

2023-08-28 04:33 UTC, FoodChain1028 approved these changes
great job!

2023-08-28 08:43 UTC, merged