refactor (userStateTransition): update anonymous component feature introduced in circom 2.1.0
FoodChain1028/Unirep pull request #9
Opened 2023-08-28 07:33 UTC by C1em3nt

## Description
This PR mainly focus on changing circuit code style.
 
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`yarn build`) was run locally in root directory and any changes were pushed
- [X] Lint (`yarn lint:fix`) was run locally in root directory and any changes were pushed

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

This PR complete anonymous component change in identity.circom

Previous Version
```
template A(n){
   signal input a, b;
   signal output c;
   c <== a*b;
}
template B(n){
   signal input in[n];
   signal out;
   component temp_a = A(n);
   temp_a.a <== in[0]; 
   temp_a.b <== in[1];
   out <== temp_a.c;
}
component main = B(2);
```

New version
```
template A(n){
   signal input a, b;
   signal output c;
   c <== a*b;
}
template B(n){
   signal input in[n];
   signal out <== A(n)(in[0],in[1]);
}
component main = B(2);
```

By doing so, we could increase the readability of the code and make the code much neater to maintain.

Issue Number: #530 

## What is the new behavior?

The behavior of the modification should not change any result from the previous version.  

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

2023-08-30 07:22 UTC, moven0831 commented on packages/circuits/circuits/userStateTransition.circom
> +    history_tree_root <== history_merkletree;
Since `history_tree_root` and `history_merkletree` represent the same thing, it provides cleaner code by substituting `history_merkletree` with `history_tree_root` and deleting line 90.

2023-08-30 07:23 UTC, moven0831 commented on packages/circuits/circuits/userStateTransition.circom
> +    signal state_merkletree <== MerkleTreeInclusionProof(STATE_TREE_DEPTH)(
Recommand to change the name from `state_merkletree` to `state_merkletree_root` to provide more detail about this variable.

2023-08-30 07:24 UTC, moven0831 commented on packages/circuits/circuits/userStateTransition.circom
> +    signal history_leaf_hasher <== Poseidon(2)([state_merkletree, epoch_tree_root]);
Recommand to change the name from `state_merkletree` to `state_merkletree_root` to provide more detail about this variable.

2023-08-30 07:29 UTC, moven0831 commented on packages/circuits/circuits/userStateTransition.circom
> +        epks[x] <== epk_out_hashers[x];
Since `epk_out_hashers` and `epks` represent the same thing, it provides cleaner code by substituting `epk_out_hashers` with `epks` and deleting `epks[x] <== epk_out_hashers[x];`.

2023-08-30 07:33 UTC, moven0831 commented on packages/circuits/circuits/userStateTransition.circom
> +    var data_check[EPOCH_KEY_NONCE_PER_EPOCH][FIELD_COUNT];
`data_check` has not been used. Consider to remove this variable.

2023-08-30 07:40 UTC, moven0831 commented on packages/circuits/circuits/userStateTransition.circom
> +    state_tree_leaf <== out_leaf_hasher;
Since `out_leaf_hasher` and `state_tree_leaf` represent the same thing, it provides cleaner code by substituting `out_leaf_hasher` with `state_tree_leaf` and deleting `state_tree_leaf <== out_leaf_hasher;`.

2023-08-30 07:45 UTC, moven0831 requested changes
One redundant variable is found and a few parts are recommended to update. Compilations and unit tests have passed successfully, great job!

2023-08-31 07:12 UTC, C1em3nt commented on packages/circuits/circuits/userStateTransition.circom
> +    history_tree_root <== history_merkletree;
Thanks >< @moven0831

2023-08-31 07:12 UTC, C1em3nt commented on packages/circuits/circuits/userStateTransition.circom
> +    signal history_leaf_hasher <== Poseidon(2)([state_merkletree, epoch_tree_root]);
Thanks >< @moven0831

2023-08-31 07:12 UTC, C1em3nt commented on packages/circuits/circuits/userStateTransition.circom
> +        epks[x] <== epk_out_hashers[x];
Thanks !! @moven0831

2023-08-31 07:28 UTC, FoodChain1028 approved these changes
LGTM!

2023-08-31 09:27 UTC, moven0831 approved these changes
LGTM

2023-08-31 09:28 UTC, merged